# Generated by Django 3.1.1 on 2020-10-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('Desc', models.TextField()),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
